#!/usr/bin/env python3
"""Pull like/comment counts for the account and write them up by posting time.

Nick's ask, early August: "we need to start being able to figure out ways to get
the statistics on how videos perform based on when they are posted." That ran
through Zapier until the task quota died, and nothing replaced it -- so the
publisher has been posting into the dark since ~8/12.

This runs in Actions (.github/workflows/stats.yml), which already holds the
token. It is deliberately a SEPARATE workflow from publishing: a stats failure
must never be able to take a posting slot down with it.

    python publisher/stats.py            snapshot + rewrite the report
    python publisher/stats.py --dry-run  print the report, write nothing

Two outputs, both committed back to the repo:

  stats/history.jsonl   one line per post per snapshot. Append-only, so the
                        trend is recoverable later -- a single current count
                        cannot tell you whether a reel is still gathering.
  stats/README.md       the readable cut: by hour, by weekday, fresh vs
                        back-catalog, and the leaderboard.

Insights (views, reach, watch time) need instagram_manage_insights, which this
token does not carry. Likes and comments are what is reachable; they are also
the only two numbers that have ever moved on this account.
"""
import argparse
import json
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import publish  # noqa: E402  -- reuse call(), creds(), log(), TZ

REPO = publish.REPO
STATS = REPO / "stats"
HISTORY = STATS / "history.jsonl"
REPORT = STATS / "README.md"
FIELDS = "id,timestamp,permalink,like_count,comments_count,media_type"


def fetch_media(ig, tok, pages=5):
    """Every post the account can see, newest first, following the cursor."""
    out, after = [], None
    for _ in range(pages):
        params = {"fields": FIELDS, "limit": 100, "access_token": tok}
        if after:
            params["after"] = after
        page = publish.call("GET", f"{ig}/media", params)
        out.extend(page.get("data", []))
        after = page.get("paging", {}).get("cursors", {}).get("after")
        if not after or not page.get("data"):
            break
    return out


def central(ts):
    """Graph hands back '2026-08-21T14:50:12+0000'. Nick thinks in Central."""
    return datetime.strptime(ts, "%Y-%m-%dT%H:%M:%S%z").astimezone(publish.TZ)


def kinds_by_permalink():
    """fresh vs back-catalog, read off the queue rather than guessed."""
    try:
        q = json.loads((REPO / "queue.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return {i["permalink"]: ("back-catalog" if publish.is_old(i) else "fresh")
            for i in q.get("items", []) if i.get("permalink")}


def snapshot(media, today):
    """Append today's counts. One line per post, so nothing is ever overwritten."""
    STATS.mkdir(exist_ok=True)
    with HISTORY.open("a", encoding="utf-8") as fh:
        for m in media:
            fh.write(json.dumps({
                "snapshot": today,
                "id": m["id"],
                "posted": m.get("timestamp"),
                "likes": m.get("like_count", 0),
                "comments": m.get("comments_count", 0),
            }, sort_keys=True) + "\n")


def _table(rows, headers):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def _mean(xs):
    return sum(xs) / len(xs) if xs else 0.0


def report(media, today):
    kinds = kinds_by_permalink()
    posts = []
    for m in media:
        if not m.get("timestamp"):
            continue
        when = central(m["timestamp"])
        posts.append({
            "when": when,
            "likes": m.get("like_count", 0),
            "comments": m.get("comments_count", 0),
            "permalink": m.get("permalink", ""),
            "kind": kinds.get(m.get("permalink", ""), "unknown"),
        })
    posts.sort(key=lambda p: p["when"], reverse=True)

    lines = ["# @nicksdadhax — likes and comments by posting time",
             "",
             f"Snapshot {today}. {len(posts)} posts. Generated by "
             "`publisher/stats.py`; do not hand-edit.",
             "",
             "Likes and comments only — views and reach need "
             "`instagram_manage_insights`, which this token does not carry.",
             ""]

    # The question Nick actually asked: does the hour matter?
    by_hour = defaultdict(list)
    for p in posts:
        by_hour[p["when"].hour].append(p["likes"])
    rows = [(f"{h:02d}:00", len(v), f"{_mean(v):.1f}", max(v))
            for h, v in sorted(by_hour.items())]
    lines += ["## By hour posted (Central)", "",
              _table(rows, ["Hour", "Posts", "Avg likes", "Best"]), ""]

    by_dow = defaultdict(list)
    for p in posts:
        by_dow[p["when"].strftime("%a")].append(p["likes"])
    order = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    rows = [(d, len(by_dow[d]), f"{_mean(by_dow[d]):.1f}")
            for d in order if by_dow[d]]
    lines += ["## By weekday", "",
              _table(rows, ["Day", "Posts", "Avg likes"]), ""]

    by_kind = defaultdict(list)
    for p in posts:
        by_kind[p["kind"]].append(p["likes"])
    rows = [(k, len(v), f"{_mean(v):.1f}") for k, v in sorted(by_kind.items())]
    lines += ["## Fresh vs back-catalog", "",
              _table(rows, ["Kind", "Posts", "Avg likes"]), ""]

    top = sorted(posts, key=lambda p: p["likes"], reverse=True)[:10]
    rows = [(p["when"].strftime("%Y-%m-%d %H:%M"), p["likes"], p["comments"],
             p["kind"], p["permalink"]) for p in top]
    lines += ["## Top 10 by likes", "",
              _table(rows, ["Posted (CT)", "Likes", "Comments", "Kind", "Link"]),
              "",
              "Sample is small and every number here is still gathering — read "
              "the shape, not the decimals.", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="print the report, write nothing")
    args = ap.parse_args()

    c = publish.creds()
    if not c["META_ACCESS_TOKEN"] or not c["IG_USER_ID"]:
        sys.exit("missing IG_USER_ID / META_ACCESS_TOKEN")
    # the error body can echo the query string back, token included
    publish._REDACT = [c["META_ACCESS_TOKEN"], c["META_PAGE_TOKEN"]]

    media = fetch_media(c["IG_USER_ID"], c["META_ACCESS_TOKEN"])
    publish.log(f"pulled {len(media)} posts")
    today = datetime.now(publish.TZ).strftime("%Y-%m-%d")
    text = report(media, today)

    if args.dry_run:
        print(text)
        return
    snapshot(media, today)
    STATS.mkdir(exist_ok=True)
    REPORT.write_text(text, encoding="utf-8")
    publish.log(f"wrote {REPORT.relative_to(REPO)} and appended to history")


if __name__ == "__main__":
    main()
